spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/bib_database?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        type:
          preferred_uuid_jdbc_type: VARCHAR